export type WordEntry = {
  hanzi: string;
  pinyin: string;
};

// 小学常见 / 幼小衔接偏友好的词汇（可随时扩充）
export const WORDS: WordEntry[] = [
  { hanzi: "妈妈", pinyin: "mā ma" },
  { hanzi: "爸爸", pinyin: "bà ba" },
  { hanzi: "姐姐", pinyin: "jiě jie" },
  { hanzi: "妹妹", pinyin: "mèi mei" },
  { hanzi: "老师", pinyin: "lǎo shī" },
  { hanzi: "同学", pinyin: "tóng xué" },
  { hanzi: "学校", pinyin: "xué xiào" },
  { hanzi: "上学", pinyin: "shàng xué" },
  { hanzi: "下课", pinyin: "xià kè" },
  { hanzi: "作业", pinyin: "zuò yè" },
  { hanzi: "书包", pinyin: "shū bāo" },
  { hanzi: "铅笔", pinyin: "qiān bǐ" },
  { hanzi: "橡皮", pinyin: "xiàng pí" },
  { hanzi: "本子", pinyin: "běn zi" },
  { hanzi: "读书", pinyin: "dú shū" },
  { hanzi: "写字", pinyin: "xiě zì" },
  { hanzi: "画画", pinyin: "huà huà" },
  { hanzi: "唱歌", pinyin: "chàng gē" },
  { hanzi: "跳舞", pinyin: "tiào wǔ" },
  { hanzi: "公主", pinyin: "gōng zhǔ" },
  { hanzi: "粉色", pinyin: "fěn sè" },
  { hanzi: "漂亮", pinyin: "piào liang" },
  { hanzi: "可爱", pinyin: "kě ài" },
  { hanzi: "开心", pinyin: "kāi xīn" },
  { hanzi: "谢谢", pinyin: "xiè xie" },
  { hanzi: "对不起", pinyin: "duì bu qǐ" },
  { hanzi: "你好", pinyin: "nǐ hǎo" },
  { hanzi: "再见", pinyin: "zài jiàn" },
  { hanzi: "早上", pinyin: "zǎo shang" },
  { hanzi: "晚上", pinyin: "wǎn shang" },
  { hanzi: "今天", pinyin: "jīn tiān" },
  { hanzi: "明天", pinyin: "míng tiān" },
  { hanzi: "昨天", pinyin: "zuó tiān" },
  { hanzi: "太阳", pinyin: "tài yáng" },
  { hanzi: "月亮", pinyin: "yuè liang" },
  { hanzi: "星星", pinyin: "xīng xing" },
  { hanzi: "天空", pinyin: "tiān kōng" },
  { hanzi: "白云", pinyin: "bái yún" },
  { hanzi: "下雨", pinyin: "xià yǔ" },
  { hanzi: "下雪", pinyin: "xià xuě" },
  { hanzi: "刮风", pinyin: "guā fēng" },
  { hanzi: "春天", pinyin: "chūn tiān" },
  { hanzi: "夏天", pinyin: "xià tiān" },
  { hanzi: "秋天", pinyin: "qiū tiān" },
  { hanzi: "冬天", pinyin: "dōng tiān" },
  { hanzi: "花朵", pinyin: "huā duǒ" },
  { hanzi: "大树", pinyin: "dà shù" },
  { hanzi: "小草", pinyin: "xiǎo cǎo" },
  { hanzi: "小猫", pinyin: "xiǎo māo" },
  { hanzi: "小狗", pinyin: "xiǎo gǒu" },
  { hanzi: "小兔", pinyin: "xiǎo tù" },
  { hanzi: "小鸟", pinyin: "xiǎo niǎo" },
  { hanzi: "金鱼", pinyin: "jīn yú" },
  { hanzi: "熊猫", pinyin: "xióng māo" },
  { hanzi: "苹果", pinyin: "píng guǒ" },
  { hanzi: "香蕉", pinyin: "xiāng jiāo" },
  { hanzi: "西瓜", pinyin: "xī guā" },
  { hanzi: "草莓", pinyin: "cǎo méi" },
  { hanzi: "牛奶", pinyin: "niú nǎi" },
  { hanzi: "面包", pinyin: "miàn bāo" },
  { hanzi: "鸡蛋", pinyin: "jī dàn" },
  { hanzi: "米饭", pinyin: "mǐ fàn" },
  { hanzi: "饺子", pinyin: "jiǎo zi" },
  { hanzi: "喝水", pinyin: "hē shuǐ" },
  { hanzi: "洗手", pinyin: "xǐ shǒu" },
  { hanzi: "刷牙", pinyin: "shuā yá" },
  { hanzi: "睡觉", pinyin: "shuì jiào" },
  { hanzi: "起床", pinyin: "qǐ chuáng" },
  { hanzi: "玩具", pinyin: "wán jù" },
  { hanzi: "娃娃", pinyin: "wá wa" },
  { hanzi: "气球", pinyin: "qì qiú" },
  { hanzi: "礼物", pinyin: "lǐ wù" },
  { hanzi: "生日", pinyin: "shēng rì" },
  { hanzi: "朋友", pinyin: "péng you" },
  { hanzi: "拥抱", pinyin: "yōng bào" },
  { hanzi: "微笑", pinyin: "wēi xiào" },
  { hanzi: "努力", pinyin: "nǔ lì" },
  { hanzi: "加油", pinyin: "jiā yóu" },
  { hanzi: "勇敢", pinyin: "yǒng gǎn" },
  { hanzi: "温柔", pinyin: "wēn róu" },
  { hanzi: "爱心", pinyin: "ài xīn" },
  { hanzi: "彩虹", pinyin: "cǎi hóng" },
  { hanzi: "糖果", pinyin: "táng guǒ" },
  { hanzi: "星光", pinyin: "xīng guāng" }
];

